{% set name = "trame-vtk" %}
{% set version = "2.8.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-vtk-{{ version }}.tar.gz
  sha256: 16f48634f420e1dfff2d662e588995e352e203f8558ac5d648a542da8f9fa70e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - trame-client

test:
  imports:
    - trame
    - trame.modules
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-vtk/
  summary: VTK widgets for trame
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
